### PR TITLE
fix: non-existent field access on error message

### LINKED ISSUE #576: "String has no .name field or method" when using unsupported CL client
Running `kurtosis run github.com/kurtosis-tech/ethereum-package --args-file network_params.yaml` with `networks_params.yaml` being:
```yaml
participants:
  - el_type: geth
    cl_type: foo
    cl_image: bar
    vc_type: lighthouse
    validator_count: null
    count: 2
```

Results in the error:
```
Evaluation error: string has no .name field or method
        at [github.com/kurtosis-tech/ethereum-package/main.star:104:55]: run
        at [github.com/kurtosis-tech/ethereum-package/src/participant_network.star:166:34]: launch_participant_network
        at [github.com/kurtosis-tech/ethereum-package/src/cl/cl_launcher.star:117:42]: launch
```

### PR DESCRIPTION
**Pull request by MegaRedHand**
Fixes #576

Now it correctly results in the error message:

```
There was an error interpreting Starlark code 
Evaluation error: fail: Unsupported launcher 'foo', need one of 'lighthouse,lodestar,nimbus,prysm,teku,grandine'
        at [github.com/kurtosis-tech/ethereum-package/main.star:104:55]: run
        at [github.com/kurtosis-tech/ethereum-package/src/participant_network.star:166:34]: launch_participant_network
        at [github.com/kurtosis-tech/ethereum-package/src/cl/cl_launcher.star:106:17]: launch
        at [0:0]: fail

Error encountered running Starlark code.
```

### CODE REVIEW

**Comment by barnabasbusa** [comment]
I’m sorry but why is “ Unsupported launcher 'foo', need one of 'lighthouse, lodestar, nimbus, prysm, teku, grandine'” not a sufficient error message? What CL client are you launching with your node?

**Comment by MegaRedHand** [comment]
There's some context in #576. I was working on integrating https://github.com/lambdaclass/lambda_ethereum_consensus with this repo and found the bug when first adding our client to the args file: "Unsupported launcher ..." wasn't being printed, but an internal error because of outdated code (each client entry had a `name` attribute before, but they no longer do).

**Review by barnabasbusa — APPROVED** [review]

**Comment by barnabasbusa** [comment]
Could you please update your branch with the latest main?

**Comment by MegaRedHand** [comment]
Done!

**Pull request merged**
