### PR TITLE
fix: Pass all beacons to the relay

### PR DESCRIPTION
**Pull request by piwonskp**
This PR adds all beacon uris to the relay following the advise in [mev-boost-relay readme](https://github.com/flashbots/mev-boost-relay#beacon-nodes--cl-clients):
> Relays are strongly advised to run multiple beacon nodes!

### CODE REVIEW

**Comment by h4ck3rk3y** [comment]
:warning: We are attempting to merge eth2-package and eth-network-package https://github.com/kurtosis-tech/eth2-package/pull/228

We request folks to not merge any PRs till we merge the above ^

**Comment by h4ck3rk3y** [comment]
Merge has complete! There are some build failures here; happy reviewing after they go green.

**Comment by piwonskp** [comment]
@h4ck3rk3y workflows fail on `kurtosis engine restart`. It appears it cannot pull kurtosis engine image

**Review by h4ck3rk3y — APPROVED** [review]
LGTM

**Pull request merged**
