### PR TITLE
feat: differentiate builder ec by suffixing it with '-builder'

### PR DESCRIPTION
**Pull request by bharath-123**
Resolves https://github.com/kurtosis-tech/ethereum-package/issues/119

### CODE REVIEW

**Comment by barnabasbusa** [comment]
please run: `kurtosis lint --format`

**Comment by bharath-123** [comment]
this is fixed @barnabasbusa

**Comment by barnabasbusa** [comment]
We currently have a merge freeze till the end of the week, can probably merge this in early next week!

**Review by barnabasbusa — APPROVED** [review]
lgtm

**Pull request merged**
